server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceshotel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Hotel-Services  
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka          