server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceshotel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
  application:
    name: Rating-services 
    
         
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka  
        