server:
  port: 8761

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceshotel
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false        